name: "FHIR IG Action"
description: "Worklow pour les IG de l'ANS"

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v3
        with:      
          path: ig

          
      # Install .NET runtime
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x.x'

          
      # Install Java runtime (only needed if you want to run the offical HL7 Java validator)
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'    
          
      - name : firely 
        shell: bash      
        run : dotnet tool install --global Firely.Terminal --version 3.0.0  

      - name: Check Firely Terminal Version
        shell: bash      
        run: |
          CHECK_FIRELY_TERMINAL_VERSION=$(fhir -v | tr '\n' ' ') # Print everything in a single line
          echo "FIRELY_TERMINAL_VERSION: $CHECK_FIRELY_TERMINAL_VERSION"

      - name: Run bake  ans.annuaire.fhir.r4
        shell: bash            
        run: |
          fhir install ans.annuaire.fhir.r4 0.2.0
          fhir bake --package ans.annuaire.fhir.r4
          
      - name: Run bake hl7.fhir.fr.core
        shell: bash            
        run: |
          fhir install hl7.fhir.fr.core 1.1.0
          fhir bake --package hl7.fhir.fr.core

          
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 📥 Download pacth fr-core
        shell: bash            
        run: |
          wget -q https://github.com/ansforge/FIG_ans.workflows/blob/main/dependency/hl7.fhir.fr.core-1.1.0.tgz?raw=true -O ./hl7.fhir.fr.core-1.1.0.tgz
          cp hl7.fhir.fr.core-1.1.0.tgz ~/.fhir/packages
          tar -xzvf ~/.fhir/packages/hl7.fhir.fr.core-1.1.0.tgz     

          
      - name: Install modules
        shell: bash            
        run: npm install -g fsh-sushi
       
      - name: Run sushi
        shell: bash      
        run: sushi ./ig
          
      - name : Install NOS
        shell: bash       
        run: |
          mkdir /home/runner/.fhir/packages/nos
          wget -q https://esante.gouv.fr/sites/default/files/media_entity/documents/NOS-Fichiers_Publics-Versions_json_fhir.zip
          unzip NOS-Fichiers_Publics-Versions_json_fhir.zip -d /home/runner/.fhir/packages/nos          

          
      - name: ✔️ Run tests
        shell: bash       
        run: java -jar validator_cli.jar  ./ig/fsh-generated/resources -ig ans.annuaire.fhir.r4#0.2.0 -ig hl7.fhir.fr.core#1.1.0 -ig /home/runner/.fhir/packages/nos -recurse -verbose -output-style compact -output rapport.html
        continue-on-error: true

      - name: Generate list using Markdown
        shell: bash       
        run: |
          echo "### Rapport de validation (validator_cli)  :rocket:" >> $GITHUB_STEP_SUMMARY
          cat rapport.html >> $GITHUB_STEP_SUMMARY
