#Publication IG/NOS
# Creation d'un dossier NOS => package_list
# Git clone le projet FIG-ANS-relase
# git submodule update --init --recursive
#Publication request à créer à chaque fois ou adapter (publication-request.json) / doit être quelque par
#https://confluence.hl7.org/display/FHIR/IG+Publication+Request+Documentation
#Repousse dans FIGans realses
#java -jar /Library/WebServer/Documents/FIG_ans-ig-release/publisher.jar -go-publish -source /Users/nicolasriss/Desktop/ANSFORGE_ans-ig/IG-NOS -web /Library/WebServer/Documents/FIG_ans-ig-release/www/ig -registry /Library/WebServer/Documents/FIG_ans-ig-release/ig-registry/fhir-ig-list.json -history /Library/WebServer/Documents/FIG_ans-ig-release/fhir-ig-history-template -templates /Library/WebServer/Documents/FIG_ans-ig-release/www/templates -temp /Library/WebServer/Documents/tmp



name: Release

on:
  workflow_call:
  workflow_dispatch:


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v3
        with:      
          path: igRepo
          
      # Install .NET runtime
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x.x'
      
      # Install Java runtime (only needed if you want to run the offical HL7 Java validator)
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'    
      - name : firely 
        run : dotnet tool install --global Firely.Terminal --version 3.0.0
        
      - name: Check Firely Terminal Version
        run: |
          CHECK_FIRELY_TERMINAL_VERSION=$(fhir -v | tr '\n' ' ') # Print everything in a single line
          echo "FIRELY_TERMINAL_VERSION: $CHECK_FIRELY_TERMINAL_VERSION"
        
      - name: Run bake  ans.annuaire.fhir.r4
        run: |
          fhir install ans.annuaire.fhir.r4 0.2.0
          fhir bake --package ans.annuaire.fhir.r4
      - name: Run bake hl7.fhir.fr.core
        run: |
          fhir install hl7.fhir.fr.core 1.1.0
          fhir bake --package hl7.fhir.fr.core
          
      # Persist the FHIR Package Cache between runners.
      # Doc: https://confluence.hl7.org/display/FHIR/FHIR+Package+Cache
      - name: 🗂️ Cache FHIR Packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.fhir/packages
          key: fhir-packages

      - name: Install modules
        run: npm install -g fsh-sushi
      - name: Run sushi
        run: sushi .
        
      # Persist the IG Publisher input-cache between runners.
      # Doc: https://build.fhir.org/ig/FHIR/ig-guidance/using-templates.html#igroot-input-cache
      - name: 🗂️ Cache IG Publisher input-cache
        uses: actions/cache@v2
        with:
          path: |
            igs/${{ env.IG }}/input-cache
          key: ig-publisher-input-cache           

      # Downloads the newest version of the IG Publisher, this could probable be cached.
      - name: 📥 Download IG Publisher
        run: wget -q https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar
        
  
      - name: Install modules
        run: npm install -g fsh-sushi
      - name: Build and test with Rake        
        run: |
          sudo apt-get install ruby-full
          sudo gem install jekyll
      # Builds the HTML page for the IG.
      - name: 🏃‍♂️ Run IG Publisher
        run : java -Xmx8192m -jar publisher.jar publisher -ig igRepo/.  -publish https://github.io/
        
        
